#pragma once

#include "nrf_gpio.h"

#define BSP_BUTTON_0       NRF_GPIO_PIN_MAP(1,13)
#define LED_1              NRF_GPIO_PIN_MAP(0,24)  // BLUE
#define LED_2              NRF_GPIO_PIN_MAP(1,0)   // GREEN
#define LED_3              NRF_GPIO_PIN_MAP(0,22)  // RED

#define BUTTON_PULL    NRF_GPIO_PIN_PULLUP

#define LEDS_NUMBER 3
#define BUTTONS_NUMBER 1

#define LEDS_LIST { LED_1, LED_2, LED_3 }
#define BUTTONS_LIST { BSP_BUTTON_0 }

#define LEDS_ACTIVE_STATE 0
#define LED_ON            0
#define LED_OFF           1

#define LEDS_INV_MASK  LEDS_MASK

#define BUTTONS_ACTIVE_STATE 1

#define BUTTON_PIN         NRF_GPIO_PIN_MAP(1,13)

#define BOARD_NAME "dictofun_v1.4"

#define SPI_FLASH_MISO_PIN NRF_GPIO_PIN_MAP(1,4)
#define SPI_FLASH_WP_PIN   NRF_GPIO_PIN_MAP(0,9)
#define SPI_FLASH_CS_PIN   NRF_GPIO_PIN_MAP(1,6)
#define SPI_FLASH_MOSI_PIN NRF_GPIO_PIN_MAP(1,2)
#define SPI_FLASH_SCK_PIN  NRF_GPIO_PIN_MAP(1,7)
#define SPI_FLASH_RST_PIN  NRF_GPIO_PIN_MAP(0,25)

#define CONFIG_IO_PDM_CLK   NRF_GPIO_PIN_MAP(0,15)
#define CONFIG_IO_PDM_DATA  NRF_GPIO_PIN_MAP(0, 17)

#define UART_TX_PIN_NUMBER (6)
#define UART_RX_PIN_NUMBER (4)

#define I2C_CLK_PIN_NUMBER  NRF_GPIO_PIN_MAP(1,9)
#define I2C_DATA_PIN_NUMBER NRF_GPIO_PIN_MAP(0,12)
#define RTC_INT_N_PIN       NRF_GPIO_PIN_MAP(0,8)
#define I2C_MODULE_IDX      1

#define LDO_LATCH_D_PIN    NRF_GPIO_PIN_MAP(0,2)
#define LDO_LATCH_CLK_PIN  NRF_GPIO_PIN_MAP(1,15)

