name: Build unit-tests
run-name: run dictofun unit-tests
on: [push]
jobs:
  checkout-the-repo:
    runs-on: [ ubuntu-latest ] #[self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        with: 
          path: ut
      - name: Checkout submodules
        run: cd ut && git submodule update --init --recursive
      - name: Build Docker image
        run: cd ut/firmware/ci && docker build -t dictofun_builder --build-arg HOST_ARCHITECTURE="x86" .
      - name: Launch unit-tests
        run: cd ut/firmware && docker run -v $(pwd):/code  dictofun_builder /bin/bash -c "mkdir -p /code/build && cd /code/build && rm -rf ./* && ../ci/build_unit_tests.sh"
