name: Build target
run-name: run dictofun target build
on: [push]
jobs:
  checkout-the-repo:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          path: target
      - run: git submodule update --init --recursive
      - run: echo "$(pwd)" && cd firmware/ci && docker build -t dictofun_builder --build-arg HOST_ARCHITECTURE="arm" .

  run-cmake-target-build:
    needs: checkout-the-repo
    runs-on: [self-hosted, linux]
    steps:
      - name: Build application
        run: cd firmware && docker run -v $(pwd):/code  dictofun_builder /bin/bash -c "mkdir -p /code/build && cd /code/build && rm -rf ./* && ../ci/build_dictofun.sh"
      - name: Upload application hex
        uses: actions/upload-artifact@v3
        with:
          name: application-hex
          path: ./firmware/build/src/targets/dictofun/Dictofun.hex
