name: Run regression tests
run-name: run regression test cases
on:
  workflow_run:
    workflows: ["Build target"]
    types:
      - completed

jobs:
  flash-application:
    runs-on: [self-hosted, linux]
    steps:
    - name: Hello
      run: echo "Hello"
    - name: Download application hex
      uses: actions/download-artifact@v3
      with:
        path: bin
        name: application-hex
