name: Run regression tests
run-name: run regression test cases
on:
  workflow_run:
    workflows: ["Build target"]
    types:
      - completed
  workflow_dispatch:
  

jobs:
  flash-application:
    runs-on: [self-hosted, linux]
    steps:
    - name: Download application hex
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build-dictofun-target.yml
        name: application-hex
    - name: Flash application hex file to the dut
      run: nrfjprog --reset --program ./Dictofun.hex --sectorerase --family NRF52 --verify
